### ISSUE TITLE
dbus-codegen-rust: Unknown character in signature Ok(UnixFd)

### ISSUE THREAD

**Issue by posborne** [diwic/dbus-rs#135]
I'm doing some work to interface with connman.  I did some introspection to generate the following XML introspection data ([manager.xml](https://github.com/diwic/dbus-rs/files/2171970/manager.xml.txt)).  When running the following I get an error:

```
$ RUST_BACKTRACE=1 dbus-codegen-rust < iface/manager.xml 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StringError("Unknown character in signature Ok(UnixFd)")', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: dbus_codegen_rust::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

I haven't dug in any deeper but am guessing that it is choking on some of the more complex signatures like this one:

```
    <method name="GetServices">
      <arg name="services" type="a(oa{sv})" direction="out"/>
    </method>
```

**Comment by diwic** [comment]
This was already fixed in git master, so I just pushed a new release of dbus-codegen (v0.2.1) where this should be fixed. Enjoy!

**Comment by posborne** [comment]
> This was already fixed in git master, so I just pushed a new release of dbus-codegen (v0.2.1) where this should be fixed. Enjoy!

Awesome, thanks!  I'll give it a go.
