### ISSUE TITLE
fdo ObjectManager GetManagedObjects method panics with multiple objects and async properties

### ISSUE THREAD

**Issue by zevweiss** [diwic/dbus-rs#416]
I encountered a crash in an application that I was able to reproduce with the test enhancement added in https://github.com/diwic/dbus-rs/pull/415:

```
$ cargo test test::object_manager_async_property
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests src/lib.rs (...)

running 1 test
test test::object_manager_async_property ... FAILED

failures:

---- test::object_manager_async_property stdout ----
thread 'test::object_manager_async_property' panicked at 'called `Option::unwrap()` on a `None` value', dbus-crossroads/src/stdimpl.rs:400:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test::object_manager_async_property' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: Timeout waiting for reply (org.freedesktop.DBus.Error.Timeout)', dbus-crossroads/src/test.rs:284:78


failures:
    test::object_manager_async_property

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 9 filtered out; finished in 5.00s

error: test failed, to rerun pass `--lib`
```

**Comment by diwic** [comment]
So this just needed the same treatment as the other one, to make sure the Context does not get lost. Thanks for the testing!
